import {receipts,available,orderHolds} from './business-model.js';
import {metrics,total,refundValue,costFields,round,stock,physical,unitCost,breakEven} from './model.js';

// One ledger drives charts and tables. Refunds belong to their return date.
export function insightData(db,from='',to='9999',event='') {
 const scope=r=>(!event||r.event===event)&&r.date>=from&&r.date<=to;
 const sales=db.sales.filter(scope),returns=db.returns.filter(scope),expenses=db.expenses.filter(scope);
 const m=metrics(db,event,from,to), ledger=[];
 sales.forEach(s=>ledger.push({date:s.date,label:s.lines.map(l=>l.name).join(', '),kind:'Sale',event:s.event,revenue:total(s),cost:s.lines.reduce((a,l)=>a+l.qty*l.cost,0),expense:0}));
 returns.forEach(r=>ledger.push({date:r.date,label:db.sales.find(s=>s.id===r.sale)?.lines[r.line]?.name||'Returned item',kind:r.restock?'Return · restocked':'Return · not restocked',event:r.event,revenue:-r.amount,cost:r.restock?-r.cost:0,expense:0}));
 expenses.forEach(e=>ledger.push({date:e.date,label:e.description||e.category||'Expense',kind:'Expense',event:e.event,revenue:0,cost:0,expense:Number(e.amount)||0}));
 const fees=db.events.filter(e=>(!event||e.id===event)&&e.date>=from&&e.date<=to&&e.status!=='Cancelled');
 fees.forEach(e=>costFields.forEach(k=>{if(Number(e[k]))ledger.push({date:e.date,label:k.replace(/([A-Z])/g,' $1'),kind:'Event cost',event:e.id,revenue:0,cost:0,expense:Number(e[k])})}));
 ledger.sort((a,b)=>a.date.localeCompare(b.date));
 const aggregate=(rows,key,value)=>{const map=new Map();rows.forEach(r=>{const k=key(r)||'Other';map.set(k,(map.get(k)||0)+value(r))});return [...map].map(([label,value])=>({label,value:round(value)})).sort((a,b)=>b.value-a.value)};
 const products=new Map();const add=(l,revenue,units)=>{const key=l.product||l.name;const p=products.get(key)||{label:l.name||'Product',category:l.category||'Other',revenue:0,units:0};p.revenue=round(p.revenue+revenue);p.units+=units;products.set(key,p)};
 sales.forEach(s=>s.lines.forEach((l,i)=>add(l,refundValue(s,i,l.qty),l.qty)));
 returns.forEach(r=>{const l=db.sales.find(s=>s.id===r.sale)?.lines[r.line];if(l)add(l,-r.amount,-r.qty)});
 const productRows=[...products.values()].sort((a,b)=>b.revenue-a.revenue);
 const payments=aggregate(receipts(db,from,to).filter(r=>!event||r.event===event).map(r=>({label:r.method,value:r.amount})),r=>r.label,r=>r.value);
 const categories=aggregate(productRows,p=>p.category,p=>p.revenue);
 const expenseRows=aggregate([...expenses.map(e=>({label:e.category||'Other',value:Number(e.amount)||0})),...fees.flatMap(e=>costFields.map(k=>({label:k.replace(/([A-Z])/g,' $1'),value:Number(e[k])||0})))],r=>r.label,r=>r.value).filter(r=>r.value!==0);
 // Daily for short ranges; monthly for longer histories. Include zero periods.
 let start=from||ledger[0]?.date||new Date().toISOString().slice(0,10),end=to==='9999'?(ledger.at(-1)?.date||start):to;
 const date=s=>new Date(s.slice(0,7)+'-01T12:00:00Z');
 const normalize=s=>{const d=date(s);d.setUTCDate(Number(s.slice(8,10)));return d};
 // Existing month filters use -31; cap it to the actual last day of that month.
 const cap=s=>{const d=date(s),last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();return s.slice(0,8)+String(Math.min(last,Number(s.slice(8,10)))).padStart(2,'0')};
 end=cap(end);const monthly=(normalize(end)-normalize(start))/86400000>62, buckets=new Map();
 if(start<=end){const d=monthly?date(start):normalize(start),finish=normalize(end);for(let n=0;d<=finish&&n<2400;n++){const k=d.toISOString().slice(0,monthly?7:10);buckets.set(k,{label:k,revenue:0,cost:0,expense:0,net:0});monthly?d.setUTCMonth(d.getUTCMonth()+1):d.setUTCDate(d.getUTCDate()+1)}}
 ledger.forEach(r=>{const k=r.date.slice(0,monthly?7:10);if(!buckets.has(k))buckets.set(k,{label:k,revenue:0,cost:0,expense:0,net:0});const b=buckets.get(k);b.revenue+=r.revenue;b.cost+=r.cost;b.expense+=r.expense});
 let cumulative=0;const series=[...buckets.values()].sort((a,b)=>a.label.localeCompare(b.label)).map(b=>{b.net=round(b.revenue-b.cost-b.expense);cumulative=round(cumulative+b.net);return {...b,revenue:round(b.revenue),cost:round(b.cost+b.expense),cumulative}});
 const times=db.timeLogs.filter(scope),hours=times.reduce((a,t)=>a+t.hours,0);
 const marketIds=[...new Set(ledger.map(r=>r.event||''))];
 const markets=marketIds.map(id=>{const rows=ledger.filter(r=>(r.event||'')===id),revenue=round(rows.reduce((a,r)=>a+r.revenue,0)),cost=round(rows.reduce((a,r)=>a+r.cost+r.expense,0));return {id,hours:times.filter(t=>(t.event||'')===id).reduce((sum,t)=>sum+Number(t.hours||0),0),label:db.events.find(e=>e.id===id)?.name||'Unassigned',revenue,cost,value:round(revenue-cost)}}).sort((a,b)=>b.value-a.value);
 const values=sales.map(total).sort((a,b)=>a-b),mean=values.length?values.reduce((a,v)=>a+v,0)/values.length:0;
 return {m,ledger,series,monthly,products:productRows,payments,categories,expenses:expenseRows,markets,hours,time:aggregate(times,t=>t.category,t=>t.hours),median:values.length?(values[Math.floor((values.length-1)/2)]+values[Math.ceil((values.length-1)/2)])/2:null,deviation:values.length?Math.sqrt(values.reduce((a,v)=>a+(v-mean)**2,0)/values.length):null,salesTotal:round(values.reduce((a,v)=>a+v,0)),salesCount:values.length};
}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['var(--chart)','var(--chart-accent)','#73958a','#b57a63','#8995ac','#9e87a0','#b9a68a','#74857b'];
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':'<p class="chart-empty">No records in this selection.</p>'}</div>`}
function panel(id,title,note,chart,headers,rows){return `<article class="panel insight-chart" data-chart="${id}"><div class="panel-title"><h3>${title}</h3><button class="text" data-chart-table="${id}" aria-expanded="false" aria-controls="table-${id}">View table ↗</button></div><p class="chart-note">${note}</p>${chart}<details id="table-${id}" class="chart-data"><summary>Data table · ${rows.length} rows</summary>${table(headers,rows)}</details></article>`}
function donut(rows,format,center){const positive=rows.filter(r=>r.value>0),sum=positive.reduce((a,r)=>a+r.value,0),negative=rows.some(r=>r.value<0);if(negative)return columns(rows,format);let offset=0;return `<div class="donut-layout"><div class="donut-figure"><svg viewBox="0 0 200 200" role="img" aria-label="${esc(center)} distribution. Exact values in the adjacent legend and table."><circle cx="100" cy="100" r="74" fill="none" stroke="var(--line)" stroke-opacity=".25" stroke-width="20"/>${positive.map((r,i)=>{const pct=r.value/sum*100,svg=`<circle class="donut-segment" cx="100" cy="100" r="74" fill="none" stroke="${colors[i%colors.length]}" stroke-width="20" pathLength="100" stroke-dasharray="${pct} ${100-pct}" stroke-dashoffset="${-offset}" transform="rotate(-90 100 100)"><title>${esc(r.label)}: ${esc(format(r.value))} (${pct.toFixed(1)}%)</title></circle>`;offset+=pct;return svg}).join('')}</svg><div class="donut-center"><strong>${esc(format(sum))}</strong><span>${esc(sum?center:'No data yet')}</span></div></div><div class="chart-legend">${positive.map((r,i)=>`<div><i style="background:${colors[i%colors.length]}"></i><span>${esc(r.label)}</span><b>${(r.value/sum*100).toFixed(1)}%</b><small>${esc(format(r.value))}</small></div>`).join('')||'<p>Add records to build this chart.</p>'}</div></div>`}
function columns(rows,format){const max=Math.max(1,...rows.map(r=>Math.abs(r.value)));return `<div class="metric-bars">${rows.map(r=>`<div class="metric-bar"><div><span>${esc(r.label)}</span><b>${esc(format(r.value))}</b></div><div class="metric-track"><i class="${r.value<0?'negative':''}" style="--bar:${Math.abs(r.value)/max*100}%"></i></div></div>`).join('')||'<p class="chart-empty">No records in this selection.</p>'}</div>`}
function lines(rows,keys,format,description='Time series; exact values available in Data table',xKey=''){if(!rows.length)return '<p class="chart-empty">No records in this selection.</p>';const values=rows.flatMap(r=>keys.map(k=>r[k.key])),lo=Math.min(0,...values),hi=Math.max(1,...values),x=i=>58+(xKey?(rows[i][xKey]-rows[0][xKey])/Math.max(1,rows.at(-1)[xKey]-rows[0][xKey]):i/Math.max(1,rows.length-1))*560,y=v=>190-(v-lo)/(hi-lo)*155;return `<div class="chart-key">${keys.map((k,i)=>`<span><i style="background:${colors[i]}"></i>${k.label}</span>`).join('')}</div><svg class="trend-chart" viewBox="0 0 650 240" role="img" aria-label="${esc(description)}"><g class="chart-grid">${[0,.5,1].map(t=>{const v=lo+(hi-lo)*t;return `<line x1="58" x2="618" y1="${y(v)}" y2="${y(v)}"/><text x="52" y="${y(v)+4}" text-anchor="end">${esc(new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(v))}</text>`}).join('')}<line class="zero-axis" x1="58" x2="618" y1="${y(0)}" y2="${y(0)}"/></g>${keys.map((k,j)=>`<polyline class="trend-line" points="${rows.map((r,i)=>`${x(i)},${y(r[k.key])}`).join(' ')}" fill="none" stroke="${colors[j]}" stroke-width="3" ${j===1?'stroke-dasharray="7 4"':''}/>${rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r[k.key])}" r="${rows.length<45?3:1.5}" fill="${colors[j]}"><title>${r.label} · ${k.label}: ${esc(format(r[k.key]))}</title></circle>`).join('')}`).join('')}${[...new Set([0,Math.floor((rows.length-1)/2),rows.length-1])].map(i=>`<text x="${x(i)}" y="222" text-anchor="${i===0?'start':i===rows.length-1?'end':'middle'}">${rows[i].label}</text>`).join('')}</svg>`}
export function renderInsights(db,from,to,money,{compact=false,event=''}={}) {
 const a=insightData(db,from,to,event),m=a.m;
 const trend=panel('trend','The rhythm of your business',`${a.monthly?'Monthly':'Daily'} revenue and total costs. Discounts and dated refunds included.`,lines(a.series,[{key:'revenue',label:'Revenue'},{key:'cost',label:'Product + event costs'}],money),['Period','Revenue','Total costs','Net profit'],a.series.map(r=>[r.label,money(r.revenue),money(r.cost),money(r.net)]));
 const costs=panel('costs','Where the money goes','Recorded expenses, including event setup costs once.',donut(a.expenses,money,'Expenses'),['Category','Expense'],a.expenses.map(r=>[r.label,money(r.value)]));
 if(compact)return `<section class="insights-section"><div class="panel-title"><div><p class="eyebrow">YOUR BUSINESS, IN NUMBERS</p><h2>A clearer picture.</h2></div><button class="text" data-action="nav" data-page="analytics">Explore analytics ↗</button></div><div class="insights-grid">${trend}${costs}</div></section>`;
 const stat=(label,value,note)=>`<div><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`;
 return `<section class="insights-section"><div class="statistics-strip">${stat('Net revenue',money(m.revenue),'After discounts and refunds')}${stat('Net profit',money(m.net),'Revenue − product costs − expenses')}${stat('Net margin',m.revenue>0?(m.net/m.revenue*100).toFixed(1)+'%':'—','Net profit ÷ positive revenue')}${stat('Units / transactions',m.units+' / '+m.transactions,'Net units / original sales')}</div><div class="insights-grid">${trend}${costs}
 ${panel('cumulative','Profit, one period at a time','Cumulative net profit within this selection. Losses remain below zero.',lines(a.series,[{key:'cumulative',label:'Cumulative net profit'}],money),['Period','Net profit','Cumulative profit'],a.series.map(r=>[r.label,money(r.net),money(r.cumulative)]))}
 ${panel('payments','How customers pay','Recorded payments and refunds by method, including deposits. Receipts can differ from delivered sales.',donut(a.payments,money,'Net receipts'),['Payment method','Net receipts'],a.payments.map(r=>[r.label,money(r.value)]))}
 ${panel('markets','Which markets pay off?','Net profit after all recorded costs. Hatched bars indicate a loss.',columns(a.markets,money),['Market','Revenue','Total costs','Net profit'],a.markets.map(r=>[r.label,money(r.revenue),money(r.cost),money(r.value)]))}
 ${panel('categories','Your product mix','Net revenue allocated after discounts and refunds. Negative balances use bars.',donut(a.categories,money,'Net revenue'),['Category','Net revenue'],a.categories.map(r=>[r.label,money(r.value)]))}
 ${panel('products','Products that earn their place','All sold products in this selection, ranked by net revenue.',columns(a.products.map(r=>({...r,value:r.revenue})),money),['Product','Category','Net units','Net revenue'],a.products.map(r=>[r.label,r.category,r.units,money(r.revenue)]))}
 ${panel('time','The hours behind the work','Logged hours in the selected period and market. No estimated hours.',donut(a.time,v=>Number(v.toFixed(2))+' h','Logged time'),['Activity','Hours'],a.time.map(r=>[r.label,r.value.toFixed(2)]))}</div>
 <article class="panel statistical-summary"><p class="eyebrow">A LITTLE MORE PERSPECTIVE</p><h3>Order statistics & your time</h3><div class="statistics-strip">${stat('Average sale',a.salesCount?money(a.salesTotal/a.salesCount):'—','Original sale totals, after discounts')}${stat('Median sale',a.median===null?'—':money(a.median),'Middle original sale value')}${stat('Sale spread (σ)',a.deviation===null?'—':money(a.deviation),'Population standard deviation')}${stat('Profit / logged hour',a.hours?money(m.net/a.hours):'—',a.hours.toFixed(2)+' hours logged; not an hourly wage')}</div><p class="chart-note">Order statistics describe original transactions before later refunds; net revenue above includes refunds on their return dates. Order receipts are recorded on their paid dates; sales and profit are recorded once when delivered.</p></article>
 ${marketScorecard(a,money)}
 ${panel('ledger','The records behind the numbers','Sales, dated refunds, product costs, additional expenses and event setup fees. This table reconciles with the charts.',`<div class="ledger-equation">${money(m.revenue)} <span>−</span> ${money(m.cogs)} <span>−</span> ${money(m.expenses)} <span>=</span> <strong>${money(m.net)}</strong></div>`,['Date','Type','Record','Revenue','Product costs','Expenses'],a.ledger.map(r=>[r.date,r.kind,r.label,money(r.revenue),money(r.cost),money(r.expense)]))}
 </section>`;
}
export function inventoryInsights(db,money){const rows=db.products.filter(p=>p.kind!=='Set').map(p=>({label:p.name,onHand:physical(db,p),available:available(db,p),held:(Number(p.reserved)||0)+orderHolds(db,p.id),value:round(physical(db,p)*unitCost(db,p)),low:available(db,p)<=Number(p.minStock||0)}));const groups=[{label:'Above minimum',value:rows.filter(r=>!r.low).length},{label:'At / below minimum',value:rows.filter(r=>r.low).length}];return panel('stock','Stock health · right now','Current individual items and variants. Sets are excluded to avoid counting their components twice; date and market filters do not apply.',donut(groups,v=>v+'','Products'),['Product','On hand','Available','Held','Cost value'],rows.map(r=>[r.label,r.onHand,r.available,r.held,money(r.value)]))}
export function bindInsights(root=document){root.querySelectorAll('.insight-chart').forEach(panel=>panel.querySelectorAll('.trend-chart,.donut-figure,.metric-bars,.production-comparison').forEach(chart=>{chart.style.cursor='pointer';chart.addEventListener('click',()=>{const details=panel.querySelector('details');details.open=true;details.querySelector('summary').focus({preventScroll:true})})}));root.querySelectorAll('[data-chart-table]').forEach(button=>{const details=root.querySelector('#table-'+button.dataset.chartTable);button.onclick=()=>{details.open=!details.open;if(details.open)details.querySelector('summary').focus({preventScroll:true})};details.addEventListener('toggle',()=>button.setAttribute('aria-expanded',String(details.open)))});}

// Scenario values reuse the calculator's rounded contribution, so the crossing
// agrees exactly with the whole-unit break-even result shown above the chart.
export function breakScenario(db,event,values,planned=0){
 const nums=['price','cost','feePercent','feeFixed'].map(k=>Number(values[k]??0));
 if(nums.some(v=>!Number.isFinite(v)||v<0)||nums[2]>100)return null;
 const result=breakEven(db,event,...nums);
 const end=Math.max(10,Math.ceil(Number(planned)||0),result.units===null?0:Math.ceil(result.units*1.4));
 if(!Number.isSafeInteger(end)||end>10000000)return null;
 const quantities=[...new Set([0,...Array.from({length:10},(_,i)=>Math.round(end*(i+1)/10)),...(result.units===null?[]:[result.units,Math.max(0,result.units-1)])])].sort((a,b)=>a-b);
 return {result,rows:quantities.map(q=>({label:String(q),quantity:q,revenue:round(q*nums[0]),cost:round(result.fixed+q*(nums[0]-result.contribution)),net:round(q*result.contribution-result.fixed)}))};
}
export function breakEvenChart(db,event,values,planned,money){
 const scenario=breakScenario(db,event,values,planned);
 if(!scenario)return '<article class="panel"><h3>Your path to break-even</h3><p>Use non-negative amounts and a payment fee from 0 to 100%. Reduce very large estimates to show a useful chart.</p></article>';
 const {result,rows}=scenario;
 const note=result.units===null?'At this price each additional sale cannot cover fixed costs. Adjust price or unit cost.':`The first whole-unit crossing is ${result.units} units. Based on your current estimates, not recorded sales.`;
 return panel('break-scenario','Your path to break-even',note,lines(rows,[{key:'revenue',label:'Estimated revenue'},{key:'cost',label:'Estimated total costs'}],money,'Break-even scenario. Horizontal axis: units sold. Vertical axis: amount. Exact values in the data table.','quantity')+'<p class="chart-note">Units sold → · Amount ↑ · Costs include fixed costs and payment fees.</p>',['Units sold','Estimated revenue','Estimated costs','Estimated profit'],rows.map(r=>[r.quantity,money(r.revenue),money(r.cost),money(r.net)]));
}
export function productionChart(rows){
 const chart=rows.length?`<div class="production-comparison"><div class="chart-key"><span><i style="background:var(--chart)"></i>Covered by available stock</span><span><i style="background:var(--chart-accent)"></i>Still to make</span></div>${rows.map(r=>{const covered=Math.min(r.required,r.available),denom=Math.max(1,r.required);return `<div class="production-comparison-row"><div><strong>${esc(r.product.name)}</strong><span>${covered} / ${r.required} covered</span></div><div class="production-track" role="img" aria-label="${esc(r.product.name)}: ${covered} covered, ${r.missing} still to make, ${r.required} required"><i style="width:${covered/denom*100}%"></i><b style="width:${r.missing/denom*100}%"></b></div><small>${r.missing?'Make '+r.missing+' more':'Ready for this market'} · ${r.other} allocated to other markets</small></div>`}).join('')}</div>`:'<p class="chart-empty">Add planned quantities to compare stock with your market needs.</p>';
 return panel('production-coverage','What is ready, what needs making?','Each bar represents that product’s remaining planned quantity. Available stock excludes held stock and other active plans; sets expand into components.',chart,['Product','Required','Available','Covered','Still to make','Other plans'],rows.map(r=>[r.product.name,r.required,r.available,Math.min(r.required,r.available),r.missing,r.other]));
}
function marketScorecard(a,money){
 const rows=a.markets;
 return `<article class="panel market-scorecard"><p class="eyebrow">COMPARE YOUR MARKETS</p><h3>The results, side by side</h3><p class="chart-note">Sorted by recorded net profit for the selected dates. Includes unassigned records. A dash means there is no positive revenue or no logged time.</p>${table(['Market','Revenue','All costs','Net profit','Net margin','Logged hours','Profit / hour'],rows.map(r=>[r.label,money(r.revenue),money(r.cost),money(r.value),r.revenue>0?(r.value/r.revenue*100).toFixed(1)+'%':'—',r.hours.toFixed(2)+' h',r.hours>0?money(r.value/r.hours):'—']))}</article>`;
}
